### ISSUE TITLE
Issues with icatcher+_models

### ISSUE THREAD

**Issue by hagi-hara** [yoterel/icatcher_plus#5]
I have questions about the models & weights. According to the instruction, these seem to be `icatcher_model.pth` and `face_classifier.pth` but we couldn't find them.

If I want to perform the iCatcher+ with pre-trained models and weights, which files should be used (I guess I should use `icatcher+_lookit.pth` and `face_classifier_lookit_weights_best.pt`)?

Also, when I specified `face_classifier_lookit_weights_best.pt` following `--fc_model`, the code didn't terminate properly although the output files were exported (it kept running). If we renamed the file from `.pt` to `.pth`, it ended as we expected.

We'd appreciate it if you could answer those issues. Thanks!

**Comment by yoterel** [comment]
> I have questions about the models & weights. According to the instruction, these seem to be `icatcher_model.pth` and `face_classifier.pth` but we couldn't find them.

All models are downloadable using the link provided under [step 3](https://github.com/yoterel/icatcher_plus#step-3-download-the-latest-network-model--weights-file) in the README file.
We will soon ad the Senegal model as well (trained on children in Senegal).

> If I want to perform the iCatcher+ with pre-trained models and weights, which files should be used (I guess I should use `icatcher+_lookit.pth` and `face_classifier_lookit_weights_best.pt`)?

Your guess is correct ! for lookit-style experiments please use these files for the model, and fc_model arguments.
If you are running iCatcher+ on videos more similar to a lab setting, consider using the cali-bw models.

> Also, when I specified `face_classifier_lookit_weights_best.pt` following `--fc_model`, the code didn't terminate properly although the output files were exported (it kept running). If we renamed the file from `.pt` to `.pth`, it ended as we expected.

This is strange, it doesn't reproduce on 2 of my machines (Windows & Linux). are you providing it with the exact path to the file? if you placed it under the models folder you should be passing:
`--fc_model models/face_classifier_lookit_weights_best.pt`

Also, can you please provide extra detail so that I might be able to reproduce this? what is the command line argument you use, which OS and what python version are you using (and if you use a virtual env, please post its library versions).
Also just to clarify, can you please send the exact error you get when the code does not terminate properly? (and if possible, the call stack).

**Comment by yoterel** [comment]
Were you able to solve this issue ?

**Comment by hagi-hara** [comment]
Thank you for replacing the files! The problem has been solved perfectly.
